### ISSUE TITLE
Spawning cars

### ISSUE THREAD

**Issue by drkm43** [d3rp-jsx/noclip-pro#2]
**Is your feature request related to a problem? Please describe.**
You cant spawn cars while noclip, car spawns but you are not getting inside it

**Describe the solution you'd like**
I think vMenu original noclip let you spawn cars and getting inside them while noclip

**Comment by d3rp-jsx** [comment]
Hi @drkm43, thank you for your feedback.
The issue has been solved with the latest commit.
