### ISSUE TITLE
Just doesn't work for me 

### ISSUE THREAD

**Issue by P4R4NORM4L** [d3rp-jsx/noclip-pro#4]
**Describe the bug**
Well Installed it, renamed it to noclip-pro, uploaded to server, set the variables that I needed in the config.
Changed the Toggle button to 'F2'
set my groups
started the resources and nothing works

yes i have rebooted the server, yes I have relogged again and again.

No Error message at all just doesn't work

Here is the config
`Config = {
    Locale = 'en',

    Controls = {
        -- FiveM IO Parameter ID: https://docs.fivem.net/docs/game-references/input-mapper-parameter-ids/keyboard/
        toggle = 'F2',
        changeSpeed = 'LSHIFT', 
        camMode = 'H', 
        -- FiveM Controls: https://docs.fivem.net/game-references/controls/
        goUp = 85, -- Q
        goDown = 48, -- Z
        turnLeft = 34, -- A
        turnRight = 35, -- D
        goForward = 32,  -- W
        goBackward = 33, -- S
    },

    Speeds = {
        -- You can add or edit existing speeds with relative label
        { speed = 0 },
        { speed = 0.5 },
        { speed = 2 },
        { speed = 5 },
        { speed = 10 },
        { speed = 15 },
    },

    Offsets = {
        y = 0.5, -- Forward and backward movement speed multiplier
        z = 0.2, -- Upward and downward movement speed multiplier
        h = 3, -- Rotation movement speed multiplier
    },

    ESX = false, -- enable ESX Legacy compatibility (ESX Legacy required)

    -- Permissions management (adding a group or a steam id requires a resource restart [or just wait a regular server restart :-)])

    -- Keep in mind that using commands such as "/setgrup" from esx will not edit database directly but will add aces to the user 
    -- so you still need to wait a bit for autosave to do its job or save the player manually in case you need this immediately

    AllowedGroups = {
        'group.owner',
        'group.head_of_management',
    },

    AllowedSteamIDs = {    },
}`

**Comment by d3rp-jsx** [comment]
Your groups look wrong. You probably don't want to include 'group.' before group name.

**Comment by P4R4NORM4L** [comment]
I've tried that

**Comment by P4R4NORM4L** [comment]
with and without group.

**Comment by d3rp-jsx** [comment]
In order to make groups work you have to enable esx compatibility mode in the config file. If you are not using esx, you may use steam ids. 

Tell me what's your framework so I can help you.

**Comment by P4R4NORM4L** [comment]
I'm non Esx I was just hooping for ace perms to work I did not activate the ESX as I thought this was for ESX only

**Comment by d3rp-jsx** [comment]
You can't use ace permissions since the group is checked after the 'noclip' command.

Use steam ID, or if you want to use groups go back to the commit where it was retrieved by MySQL.

If you are running a different framework than ESX, I may provide support for it.

**Comment by P4R4NORM4L** [comment]
I need it to support Ace perms if possible so that i don't need to get every single steamID of my staff to put it in

**Comment by P4R4NORM4L** [comment]
it's just an FX server

**Comment by d3rp-jsx** [comment]
In that case you have many options:
- use steam ids
- go back to the commit where player group was retrieved through mysql with group column in the user table 
- delete server side file and adjust client side to use the right event so you can use ace permissions.

**Comment by P4R4NORM4L** [comment]
I don't use mySQL for this type of server and don't require one
